apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: stable-4.12
  clusterID: 42fa5e25-0826-42d8-b589-681948b2e59b
  desiredUpdate:
      version: 4.12.21
